### ISSUE TITLE
Does not work on Qlik Sense 3.1 SR2?

### ISSUE THREAD

**Issue by sc305495** [brianwmunz/svgReader-QlikSense#15]
In Qlik Sense Desktop 3.1 SR2 (10.7.1) this extension displays an error "The visualization was not found on the server: svgReader".

Has anyone else gotten this visualization to display correctly in the latest version of Qlik Sense 3.1?  I have this installed in the Documents/Qlik/Sense/Exensions/svgReader-QlikSense-Master/svgReader folder...

**Comment by brianwmunz** [comment]
This has been fixed by @yianni-ververis thanks

**Comment by stschwarz** [comment]
Hey, what was the resolution to this issue?

**Comment by brianwmunz** [comment]
The themes got moved in SR2 so it caused it to break.  Code was updated in svgReader.js to set it to the proper location.  YOu can see the old code commented there.

**Comment by stschwarz** [comment]
okay so if i re-download the extension I should be good to go?

**Comment by brianwmunz** [comment]
Yup only issue is that it now won't work on older versions :-/ . But that's an easy fix...you can just comment out the new code and uncomment the old code.

**Comment by stschwarz** [comment]
okay perfect. thank you
